apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: heyMonitor
    release: prometheus
  name: hey-metrics
  namespace: default
spec:
  jobLabel: job
  endpoints:
  - interval: 30s
    port: hey-port
  selector:
    matchLabels:
      squad: frontend 
